version: '3'

services:
  app:
    container_name: server
    restart: always
    build: .
    ports:
      - '8082:8082'
    links:
      - mongo
  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - '27017:27017'
